# Generated by Django 5.1.7 on 2025-05-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='card',
            field=models.CharField(default='None', max_length=25),
        ),
    ]
